// Generated by make_cookies.py
window.COOKIES = [
  {
    "name": "1",
    "src": "images/1.png"
  },
  {
    "name": "2",
    "src": "images/2.png"
  },
  {
    "name": "3",
    "src": "images/3.png"
  }
];
