// Generated by make_cookies.py - run it again after changing the images folder.
window.COOKIES = [
  {
    "name": "Angel Cookie",
    "rarity": "Common",
    "src": "images/01-common/angel-cookie.webp"
  },
  {
    "name": "Beet Cookie",
    "rarity": "Common",
    "src": "images/01-common/beet-cookie.webp"
  },
  {
    "name": "GingerBrave",
    "rarity": "Common",
    "src": "images/01-common/GingerBrave.webp"
  },
  {
    "name": "Muscle Cookie",
    "rarity": "Common",
    "src": "images/01-common/muscle-cookie.webp"
  },
  {
    "name": "Ninja Cookie",
    "rarity": "Common",
    "src": "images/01-common/ninja-cookie.webp"
  },
  {
    "name": "Strawberry Cookie",
    "rarity": "Common",
    "src": "images/01-common/strawberry-cookie.webp"
  },
  {
    "name": "Wizard Cookie",
    "rarity": "Common",
    "src": "images/01-common/wizard-cookie.webp"
  },
  {
    "name": "Adventurer Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/adventurer-cookie.webp"
  },
  {
    "name": "Alchemist Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/alchemist-cookie.webp"
  },
  {
    "name": "Avocado Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/avocado-cookie.webp"
  },
  {
    "name": "Blackberry Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/blackberry-cookie.webp"
  },
  {
    "name": "Carrot Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/carrot-cookie.webp"
  },
  {
    "name": "Cherry Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/cherry-cookie.webp"
  },
  {
    "name": "Clover Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/clover-cookie.webp"
  },
  {
    "name": "Custard Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/custard-cookie.webp"
  },
  {
    "name": "Devil Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/devil-cookie.webp"
  },
  {
    "name": "Gumball Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/gumball-cookie.webp"
  },
  {
    "name": "Knight Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/knight-cookie.webp"
  },
  {
    "name": "Onion Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/onion-cookie.webp"
  },
  {
    "name": "Pancake Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/pancake-cookie.webp"
  },
  {
    "name": "Princess Cookie",
    "rarity": "Rare",
    "src": "images/02-rare/princess-cookie.webp"
  },
  {
    "name": "Cream Ferret",
    "rarity": "Special",
    "src": "images/03-special/Cream-Ferret.webp"
  },
  {
    "name": "Icicle Yeti",
    "rarity": "Special",
    "src": "images/03-special/Icicle-Yeti.webp"
  },
  {
    "name": "Marshmallow Bunny",
    "rarity": "Special",
    "src": "images/03-special/Marshmallow-Bunny.webp"
  },
  {
    "name": "Snapdragon",
    "rarity": "Special",
    "src": "images/03-special/Snapdragon.webp"
  },
  {
    "name": "Affogato Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/affogato-cookie.webp"
  },
  {
    "name": "Agar Agar Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/agar-agar-cookie.webp"
  },
  {
    "name": "Almond Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/almond-cookie.webp"
  },
  {
    "name": "Ash Salt Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/ash-salt-cookie.webp"
  },
  {
    "name": "Asphodel Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/asphodel-cookie.webp"
  },
  {
    "name": "Black Forest Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/black-forest-cookie.webp"
  },
  {
    "name": "Black Lemonade Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/black-lemonade-cookie.webp"
  },
  {
    "name": "Black Raisin Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/black-raisin-cookie.webp"
  },
  {
    "name": "Black Sapphire Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/black-sapphire-cookie.webp"
  },
  {
    "name": "Blueberry Pie Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/blueberry-pie-cookie.webp"
  },
  {
    "name": "Burnt Cheese Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/burnt-cheese-cookie.webp"
  },
  {
    "name": "Butter Roll Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/butter-roll-cookie.webp"
  },
  {
    "name": "Candy Apple Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/candy-apple-cookie.webp"
  },
  {
    "name": "Candy Diver Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/candy-diver-cookie.webp"
  },
  {
    "name": "Captain Caviar Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/captain-caviar-cookie.webp"
  },
  {
    "name": "Caramel Arrow Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/caramel-arrow-cookie.webp"
  },
  {
    "name": "Caramel Choux Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/caramel-choux-cookie.webp"
  },
  {
    "name": "Carol Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/carol-cookie.webp"
  },
  {
    "name": "Charcoal Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/charcoal-cookie.webp"
  },
  {
    "name": "Cherry Blossom Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cherry-blossom-cookie.webp"
  },
  {
    "name": "Chess Choco Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/chess-choco-cookie.webp"
  },
  {
    "name": "Chili Pepper Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/chili-pepper-cookie.webp"
  },
  {
    "name": "Choco Drizzle Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/choco-drizzle-cookie.webp"
  },
  {
    "name": "Cloud Haetae Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cloud-haetae-cookie.webp"
  },
  {
    "name": "Cocoa Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cocoa-cookie.webp"
  },
  {
    "name": "Cotton Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cotton-cookie.webp"
  },
  {
    "name": "Cream Puff Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cream-puff-cookie.webp"
  },
  {
    "name": "Cream Soda Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cream-soda-cookie.webp"
  },
  {
    "name": "Cream Unicorn Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/cream-unicorn-cookie.webp"
  },
  {
    "name": "Croissant Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/croissant-cookie.webp"
  },
  {
    "name": "Crunchy Chip Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/crunchy-chip-cookie.webp"
  },
  {
    "name": "Crème Brûlée Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/creme-brulee-cookie.webp"
  },
  {
    "name": "Dark Choco Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/dark-choco-cookie.webp"
  },
  {
    "name": "Eclair Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/eclair-cookie.webp"
  },
  {
    "name": "Espresso Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/espresso-cookie.webp"
  },
  {
    "name": "Fettuccine Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/fettuccine-cookie.webp"
  },
  {
    "name": "Fig Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/fig-cookie.webp"
  },
  {
    "name": "Financier Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/financier-cookie.webp"
  },
  {
    "name": "Fresh Apple Faerie",
    "rarity": "Epic",
    "src": "images/04-epic/fresh-apple-faerie.webp"
  },
  {
    "name": "Frilled Jellyfish Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/frilled-jellyfish-cookie.webp"
  },
  {
    "name": "Golden Osmanthus Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/golden-osmanthus-cookie.webp"
  },
  {
    "name": "Grapefruit Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/grapefruit-cookie.webp"
  },
  {
    "name": "Green Tea Mousse Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/green-tea-mousse-cookie.webp"
  },
  {
    "name": "Herb Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/herb-cookie.webp"
  },
  {
    "name": "Jagae Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/jagae-cookie.webp"
  },
  {
    "name": "Kouign-Amann Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/kouign-amann-cookie.webp"
  },
  {
    "name": "Kumiho Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/kumiho-cookie.webp"
  },
  {
    "name": "Latte Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/latte-cookie.webp"
  },
  {
    "name": "Lemon Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/lemon-cookie.webp"
  },
  {
    "name": "Licorice Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/licorice-cookie.webp"
  },
  {
    "name": "Lilac Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/lilac-cookie.webp"
  },
  {
    "name": "Lime Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/lime-cookie.webp"
  },
  {
    "name": "Linzer Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/linzer-cookie.webp"
  },
  {
    "name": "Litmus Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/litmus-cookie.webp"
  },
  {
    "name": "Macaron Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/macaron-cookie.webp"
  },
  {
    "name": "Madeleine Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/madeleine-cookie.webp"
  },
  {
    "name": "Mala Sauce Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mala-sauce-cookie.webp"
  },
  {
    "name": "Mango Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mango-cookie.webp"
  },
  {
    "name": "Manju Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/manju-cookie.webp"
  },
  {
    "name": "Matcha Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/matcha-cookie.webp"
  },
  {
    "name": "Menthol Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/menthol-cookie.webp"
  },
  {
    "name": "Mercurial Knight Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mercurial-knight-cookie.webp"
  },
  {
    "name": "Milk Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/milk-cookie.webp"
  },
  {
    "name": "Milky Way Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/milky-way-cookie.webp"
  },
  {
    "name": "Mint Choco Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mint-choco-cookie.webp"
  },
  {
    "name": "Mogra Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mogra-cookie.webp"
  },
  {
    "name": "Mold Dough Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mold-dough-cookie.webp"
  },
  {
    "name": "Moon Rabbit Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/moon-rabbit-cookie.webp"
  },
  {
    "name": "Mozzarella Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/mozzarella-cookie.webp"
  },
  {
    "name": "Nutmeg Tiger Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/nutmeg-tiger-cookie.webp"
  },
  {
    "name": "Okchun Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/okchun-cookie.webp"
  },
  {
    "name": "Olive Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/olive-cookie.webp"
  },
  {
    "name": "Orange Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/orange-cookie.webp"
  },
  {
    "name": "Parfait Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/parfait-cookie.webp"
  },
  {
    "name": "Pastry Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pastry-cookie.webp"
  },
  {
    "name": "Pavlova Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pavlova-cookie.webp"
  },
  {
    "name": "Peach Blossom Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/peach-blossom-cookie.webp"
  },
  {
    "name": "Peppermint Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/peppermint-cookie.webp"
  },
  {
    "name": "Pinecone Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pinecone-cookie.webp"
  },
  {
    "name": "Poison Mushroom Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/poison-mushroom-cookie.webp"
  },
  {
    "name": "Pom Pom Dough Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pom-pom-dough-cookie.webp"
  },
  {
    "name": "Pomegranate Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pomegranate-cookie.webp"
  },
  {
    "name": "Prophet Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/prophet-cookie.webp"
  },
  {
    "name": "Prune Juice Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/prune-juice-cookie.webp"
  },
  {
    "name": "Pudding à la Mode Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pudding-a-la-mode-cookie.webp"
  },
  {
    "name": "Pulpo Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pulpo-cookie.webp"
  },
  {
    "name": "Pumpkin Pie Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/pumpkin-pie-cookie.webp"
  },
  {
    "name": "Purple Yam Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/purple-yam-cookie.webp"
  },
  {
    "name": "Raspberry Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/raspberry-cookie.webp"
  },
  {
    "name": "Rebel Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/rebel-cookie.webp"
  },
  {
    "name": "Red Osmanthus Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/red-osmanthus-cookie.webp"
  },
  {
    "name": "Red Velvet Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/red-velvet-cookie.webp"
  },
  {
    "name": "Rockstar Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/rockstar-cookie.webp"
  },
  {
    "name": "Royal Margarine Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/royal-margarine-cookie.webp"
  },
  {
    "name": "Rye Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/rye-cookie.webp"
  },
  {
    "name": "Salt Cellar Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/salt-cellar-cookie.webp"
  },
  {
    "name": "Schwarzwälder Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/schwarzwalder-cookie.webp"
  },
  {
    "name": "Seltzer Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/seltzer-cookie.webp"
  },
  {
    "name": "Silverbell Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/silverbell-cookie.webp"
  },
  {
    "name": "Smoked Cheese Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/smoked-cheese-cookie.webp"
  },
  {
    "name": "Snow Sugar Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/snow-sugar-cookie.webp"
  },
  {
    "name": "Sorbet Shark Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/sorbet-shark-cookie.webp"
  },
  {
    "name": "Space Doughnut Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/space-doughnut-cookie.webp"
  },
  {
    "name": "Sparkling Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/sparkling-cookie.webp"
  },
  {
    "name": "Squid Ink Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/squid-ink-cookie.webp"
  },
  {
    "name": "Star Coral Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/star-coral-cookie.webp"
  },
  {
    "name": "Strawberry Crepe Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/strawberry-crepe-cookie.webp"
  },
  {
    "name": "Street Urchin Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/street-urchin-cookie.webp"
  },
  {
    "name": "Sugarfly Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/sugarfly-cookie.webp"
  },
  {
    "name": "Tarte Tatin Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/tarte-tatin-cookie.webp"
  },
  {
    "name": "Tea Knight Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/tea-knight-cookie.webp"
  },
  {
    "name": "Tiger Lily Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/tiger-lily-cookie.webp"
  },
  {
    "name": "Twizzly Gummy Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/twizzly-gummy-cookie.webp"
  },
  {
    "name": "Vampire Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/vampire-cookie.webp"
  },
  {
    "name": "Wedding Cake Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/wedding-cake-cookie.webp"
  },
  {
    "name": "Werewolf Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/werewolf-cookie.webp"
  },
  {
    "name": "Wildberry Cookie",
    "rarity": "Epic",
    "src": "images/04-epic/wildberry-cookie.webp"
  },
  {
    "name": "Camellia Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/camellia-cookie.webp"
  },
  {
    "name": "Capsaicin Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/capsaicin-cookie.webp"
  },
  {
    "name": "Clotted Cream Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/clotted-cream-cookie.webp"
  },
  {
    "name": "Crimson Coral Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/crimson-coral-cookie.webp"
  },
  {
    "name": "Doughael Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/doughael-cookie.webp"
  },
  {
    "name": "Elder Faerie Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/elder-faerie-cookie.webp"
  },
  {
    "name": "Oyster Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/oyster-cookie.webp"
  },
  {
    "name": "Povidone-Iodine Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/povidone-iodine-cookie.webp"
  },
  {
    "name": "Sherbet Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/sherbet-cookie.webp"
  },
  {
    "name": "Shining Glitter Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/shining-glitter-cookie.webp"
  },
  {
    "name": "Stardust Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/stardust-cookie.webp"
  },
  {
    "name": "Time Shadow Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/time-shadow-cookie.webp"
  },
  {
    "name": "Venom Dough Cookie",
    "rarity": "Super Epic",
    "src": "images/05-super-epic/venom-dough-cookie.webp"
  },
  {
    "name": "Ananas Dragon Cookie",
    "rarity": "Dragon",
    "src": "images/06-dragon/ananas-dragon-cookie.webp"
  },
  {
    "name": "Pitaya Dragon Cookie",
    "rarity": "Dragon",
    "src": "images/06-dragon/pitaya-dragon-cookie.webp"
  },
  {
    "name": "Black Pearl Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/black-pearl-cookie.webp"
  },
  {
    "name": "Fire Spirit Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/fire-spirit-cookie.webp"
  },
  {
    "name": "Frost Queen Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/frost-queen-cookie.webp"
  },
  {
    "name": "Millennial Tree Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/millennial-tree-cookie.webp"
  },
  {
    "name": "Moonlight Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/moonlight-cookie.webp"
  },
  {
    "name": "Nether Queen Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/nether-queen-cookie.webp"
  },
  {
    "name": "Sea Fairy Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/sea-fairy-cookie.webp"
  },
  {
    "name": "Stormbringer Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/stormbringer-cookie.webp"
  },
  {
    "name": "Sugar Swan Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/sugar-swan-cookie.webp"
  },
  {
    "name": "Sugar Swan Cookie (Swan Form)",
    "rarity": "Legendary",
    "src": "images/07-legendary/sugar-swan-form-cookie.webp"
  },
  {
    "name": "Timekeeper Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/timekeeper-cookie.webp"
  },
  {
    "name": "Wind Archer Cookie",
    "rarity": "Legendary",
    "src": "images/07-legendary/wind-archer-cookie.webp"
  },
  {
    "name": "Awakened Dark Cacao Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/awakened-dark-cacao-cookie.webp"
  },
  {
    "name": "Awakened Golden Cheese Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/awakened-golden-cheese-cookie.webp"
  },
  {
    "name": "Awakened Hollyberry Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/awakened-hollyberry-cookie.webp"
  },
  {
    "name": "Awakened Pure Vanilla Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/awakened-pure-vanilla-cookie.webp"
  },
  {
    "name": "Awakened White Lily Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/awakened-white-lily-cookie.webp"
  },
  {
    "name": "Dark Cacao Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/dark-cacao-cookie.webp"
  },
  {
    "name": "Golden Cheese Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/golden-cheese-cookie.webp"
  },
  {
    "name": "Hollyberry Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/hollyberry-cookie.webp"
  },
  {
    "name": "Pure Vanilla Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/pure-vanilla-cookie.webp"
  },
  {
    "name": "White Lily Cookie",
    "rarity": "Ancient",
    "src": "images/08-ancient/white-lily-cookie.webp"
  },
  {
    "name": "Burning Spice Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/burning-spice-cookie.webp"
  },
  {
    "name": "Eternal Sugar Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/eternal-sugar-cookie.webp"
  },
  {
    "name": "Mystic Flour Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/mystic-flour-cookie.webp"
  },
  {
    "name": "Rajapendra Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/rajapendra-cookie.webp"
  },
  {
    "name": "Shadow Milk Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/shadow-milk-cookie.webp"
  },
  {
    "name": "Silent Salt Cookie",
    "rarity": "Beast",
    "src": "images/09-beast/silent-salt-cookie.webp"
  },
  {
    "name": "Dark Enchantress Cookie",
    "rarity": "Witch",
    "src": "images/10-witch/dark-enchantress-cookie.webp"
  }
];
