#!/usr/bin/env python3
"""Scans ./images and writes cookies.js. Run again whenever images change.
Optional: create names.json like {"1": "Gingerbrave", "2": "Pure Vanilla"}
to give numbered images real names."""
import json, re
from pathlib import Path

EXT = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".avif"}
root = Path(__file__).parent
names_file = root / "names.json"
names = json.loads(names_file.read_text(encoding="utf-8")) if names_file.exists() else {}

def natural(p):  # 1, 2, 10 instead of 1, 10, 2
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", p.stem)]

cookies = []
for f in sorted((root / "images").iterdir(), key=natural):
    if f.suffix.lower() in EXT:
        name = names.get(f.stem) or re.sub(r"[-_]+", " ", f.stem).strip().title()
        cookies.append({"name": name, "src": f"images/{f.name}"})

(root / "cookies.js").write_text(
    "// Generated by make_cookies.py\nwindow.COOKIES = "
    + json.dumps(cookies, indent=2, ensure_ascii=False) + ";\n", encoding="utf-8")
print(f"Wrote cookies.js with {len(cookies)} cookies")
